### ISSUE TITLE
Documentar cómo agregar un framework personalizado a Platformio

### ISSUE THREAD

**Issue by Karosuo** [CoDePretzel/CoDePretzel_Framework#19]
Hasta ahora, parece que para lograr dicho objetivo es necesario cumplir con lo siguientes elementos:

- Crear un package para codepretzel_framework, incluye solo el folder interface_portable, solo las que no tienen custom name
- Crear un package para el código de MCC, todo el código generado por MCC
- Cómo relacionas ambos package en el mismo framework?, solo lo que asignes en el "platform"?
- Crear un ejemplo de uso del framework y del package MCC unidos, el hola led y agregarlo como ejemplo al framework package
- Crear un platform para AVR128DA copiando lo de AtmelMegaAVR y alguna si encuentro, agregarle soporte a Arduino y al de CoDe Pretzel
- Agregar los scripts de build para para los packages de MCC y del framework, que se usarán en el platform (no es seguro que tengan que tener uno diferente, a lo mejor se puede usar el mismo o se pueden integrar en un package de packages)
- Crear un board (si es que no existe ya el AVR128DA48 Curiosity Nano), para agregarle soporte a Arduino y al de CoDe Pretzel
- Crear un proyecto nuevo, seleccionar la board custom y seleccionar el ejemplo que incluye el framework, debería de funcionar la compilación

**Nota:**
Es posible que por ende, otros issues que originalmente estaban separados, se vean resueltos implicitamente, hay que tener precaución de hacer la nota y la referencia en ellos de que fueron cubiertos por este

**Comment by emmanuelnunoe** [comment]
**Guia para agregar un nuevo framework a PlatformIO**
https://community.platformio.org/t/adding-a-new-framework-to-platformio/297/2

**Comment by Karosuo** [comment]
Hasta ahora parece que el `instrumento` de `framework` para PlatformIO está bastante asociado a la plataforma donde va a ser usado, al menos en la documentación.
Pero, su independencia viene de que es tratado como un `package` y administrado por el gestor de dependencias de PlatformIO.
Por lo tanto agrego dos referencias a
* Packages
https://community.platformio.org/t/working-with-custom-packages/19097
* Manejo de dependencias
https://docs.platformio.org/en/latest/librarymanager/dependencies.html
https://docs.platformio.org/en/latest/projectconf/section_env_library.html#projectconf-lib-deps

**Comment by Karosuo** [comment]
Continuando con el comentario anterior
Para tener un framework custom disponible en el PlatformIO registry (el lugar donde se suben y administran los `packages` para que sean públicamente accesibles através de PlatformIO, relacionado con #20 ), es necesario crear un `package`.

Sin embargo, hay 2 maneras de usarlo.

1. Incluirlo como parámetro `lib_deps` en `platformio.json`, que significaria incluirlo manualmente en cada proyecto.
2. Incluirlo en un `platform` custom que ayude a pre instalarlo (y otras dependencias) cada que se seleccione dicho `platform` en un proyecto nuevo, a través de una `board` (lo cual significa que también necesita una board custom)

**Nota:** Es importante saber el `platform` y la `board` custom que se mencionan arriba, pueden ser copy/paste de uno existente, por ejemplo `atmelmegaavr` y `AVR128DA48.json` respectivamente, solo cambiando las configuraciones pertinentes para que incluyan el nuevo framework

**Comment by Karosuo** [comment]
Qué pasa si queremos agregar un toolchain custom?, bueno, es bastante confuso pero parece que es configuración entre el `framework` el `platform` y los `package`s que correspondan.
https://community.platformio.org/t/distributing-custom-toolchain-platform/24534/2
Aún no llego a esa parte, así que faltan preguntas por resolver.

**Comment by Karosuo** [comment]
Al parecer me brinqué una documentación importante para entender la configuración de contextos de PlatformIO
https://docs.platformio.org/en/latest/scripting/construction_environments.html#scripting-envs
También sugieren la documentación de `advanced scripting`, pero no creo que sea estrictamente necesario para esta parte aún (aunque quizá me equivoque porque para crear los scripts de build para el `platform` custom, probablemente sí se vaya a requerir)

**Comment by Karosuo** [comment]
También es importante mencionar que parece que Platformio ya tiene una forma de cómo organizar packages que son dependientes de código de HAL
https://docs.platformio.org/en/latest/manifests/library-json/fields/build/extrascript.html

*EDIT*
Esta forma indica la manera de agregar un código HAL que viviría en el arbol de directorios del proyecto, según me parece, no está usando un package externo, no lo está incluyendo en platformio.ini, ni en `lib_deps`?
